name: egm722-assignment
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - geopandas
  - jupyterlab
  - ipywidgets
  - rasterio
  - folium
  - ipympl
  - earthaccess
  - rasterstats
  - shapely